apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-api-deployment
  labels:
    app: movie-analyst-api
    tier: backEnd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-analyst-api
      tier: backEnd
#this specifies the pod, so it should be assoc with the registry
  template:
    metadata:
      labels:
        app: movie-analyst-api
        tier: backEnd
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: movie-analyst-api
          imagePullPolicy: Always
          image: 34.220.121.141:5000/backimage
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: 123456abcd
          ports:
          - containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5 
              #timeoutSeconds: 1      
