apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-ui-deployment
  labels:
    tes: liveness
    app: movie-analyst-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-analyst-ui
#this specifies the pod, so it should be assoc with the registry
  template:
    metadata:
      labels:
        app: movie-analyst-ui
    spec:
      containers:
      - name: movie-analyst-ui
        image: 18.237.52.151:5000/frontimage
      imagePullSecrets:
      - name: registrySecret
        ports:
        - containerPort: 3030
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5 
          #timeoutSeconds: 1      