apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-ui-deployment
  labels:
    app: movie-analyst-ui
    tier: frontEnd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-analyst-ui
      tier: frontEnd
#this specifies the pod, so it should be assoc with the registry
  template:
    metadata:
      labels:
        app: movie-analyst-ui
        tier: frontEnd
    spec:
      imagePullPolicy: Always
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: movie-analyst-ui
          image: 34.220.121.141:5000/frontimage
          env:
          - name: BACKEND_URL
            value: "service-backEnd"      
          ports:
          - containerPort: 3030
          livenessProbe:
            tcpSocket:
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3030
            initialDelaySeconds: 5
            periodSeconds: 5 
            #timeoutSeconds: 1      
