apiVersion: v1
kind: Service
metadata:
  name: service-back
spec:
  selector:
    app: movie-analyst-api
    tier: backEnd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: clusterIP 