apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  selector:
    app: movie-analyst-ui
    tier: frontEnd
  ports:
    - protocol: TCP
      port: 3030
      nodePort: 30100
      targetPort: 3030
  type: NodePort